train: ../dataset_training/relabel_pixelLevelAugment_dataset_ver2/images/train # relative path to train images
val: ../dataset_training/relabel_pixelLevelAugment_dataset_ver2/images/val # relative path to val images
test: ./dataset/images/public_test  # relative path to public test images

# Classes
# Please don't change
num_class: 3  # number of classes
# names: ['0', '1', '2']
names: ['no_mask', 'mask', 'incorrect_mask']
